"""Generate ARCHITECTURE.md — a Mermaid module-dependency graph of the project.

Runs on every commit via the pre-commit hook. AST-based (parses import
statements as text; never imports the modules), so it's fast and does NOT pull
torch/models. Mermaid renders natively on GitHub — no PlantUML/Java needed.
Deterministic + timestamp-free: the file only changes when the real import
graph changes, so commits stay noise-free.

    uv run python scripts/gen_architecture.py
"""

import ast
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
# top-level project packages/modules; an import is "internal" iff its first
# dotted component is one of these
PACKAGES = (
    "config",
    "prompts",
    "rag",
    "ingestion",
    "evals",
    "finetuning",
    "scripts",
    "agent",
    "api",
)
OUT = ROOT / "ARCHITECTURE.md"


def _module_id(path: Path) -> str:
    """rag/hybrid.py -> 'rag.hybrid', config.py -> 'config'."""
    rel = path.relative_to(ROOT).with_suffix("")
    return ".".join(rel.parts)


def discover_modules() -> dict[str, Path]:
    mods: dict[str, Path] = {}
    for pkg in PACKAGES:
        file_mod = ROOT / f"{pkg}.py"  # top-level module like config.py
        if file_mod.is_file():
            mods[_module_id(file_mod)] = file_mod
        dir_pkg = ROOT / pkg
        if dir_pkg.is_dir():
            for f in dir_pkg.rglob("*.py"):
                if f.name == "__init__.py":  # packages are shown via their members
                    continue
                mods[_module_id(f)] = f
    return mods


def _imports(path: Path) -> set[str]:
    """All imported dotted names in a file (module-level AND lazy/in-function)."""
    tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    names: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for a in node.names:
                names.add(a.name)
        elif isinstance(node, ast.ImportFrom) and node.module and node.level == 0:
            for a in node.names:
                names.add(f"{node.module}.{a.name}")
                names.add(node.module)
    return names


def build_edges(mods: dict[str, Path]) -> set[tuple[str, str]]:
    known = set(mods)
    edges: set[tuple[str, str]] = set()
    for mod, path in mods.items():
        for imp in _imports(path):
            if imp.split(".", 1)[0] not in PACKAGES:
                continue
            # resolve to the most specific known module: 'rag.generate.generate'
            # (a function) collapses to the module 'rag.generate'
            target = imp if imp in known else imp.rsplit(".", 1)[0]
            if target in known and target != mod:
                edges.add((mod, target))
    return edges


def _node(mod: str) -> str:
    return mod.replace(".", "_")


def render(mods: dict[str, Path], edges: set[tuple[str, str]]) -> str:
    by_pkg: dict[str, list[str]] = {}
    for mod in mods:
        pkg = mod.split(".", 1)[0] if "." in mod else "root"
        by_pkg.setdefault(pkg, []).append(mod)

    lines = ["graph LR"]
    for pkg in sorted(by_pkg):
        lines.append(f"  subgraph {pkg}")
        for mod in sorted(by_pkg[pkg]):
            label = mod.split(".", 1)[1] if "." in mod else mod
            lines.append(f'    {_node(mod)}["{label}"]')
        lines.append("  end")
    for src, dst in sorted(edges):
        lines.append(f"  {_node(src)} --> {_node(dst)}")

    return "\n".join(
        [
            "# Architecture",
            "",
            "> Auto-generated by `scripts/gen_architecture.py` (pre-commit hook). Do NOT edit by hand.",
            "> Nodes = project modules, edges = imports (incl. lazy/deferred). GitHub renders this inline.",
            "",
            "```mermaid",
            *lines,
            "```",
            "",
        ]
    )


def main() -> int:
    mods = discover_modules()
    if not mods:
        print("no modules found", file=sys.stderr)
        return 1
    content = render(mods, build_edges(mods))
    changed = not OUT.exists() or OUT.read_text(encoding="utf-8") != content
    OUT.write_text(content, encoding="utf-8")
    print(f"{'updated' if changed else 'unchanged'}: {OUT.name} ({len(mods)} modules)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
